#!/bin/bash
echo method1
dd if=/dev/zero of=/tmp/16GB bs=1M count=16000
dd if=/dev/zero of=/tmp/16GB bs=10M count=1600
dd if=/dev/zero of=/tmp/16GB bs=100M count=160
dd if=/dev/zero of=/tmp/16GB bs=1G count=16
rm /tmp/16GB

echo method2
fio --name=writefile --size=16G --filesize=16G --filename=/tmp/16GB --bs=1M --nrfiles=1 --direct=1 --sync=0 --randrepeat=0 --rw=write --refill_buffers --end_fsync=1 --iodepth=200 --ioengine=libaio
rm /tmp/16GB

