[project]
name = "phaser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "python-bladerf>=1.4.0",
    "scipy>=1.16.2",
    "setuptools>=80.9.0",
    "sigmf>=1.2.10",
]
